# data
meta_id: meta_subject_h36m
#cnn_feat: 'subject_h36m'
#expert_feat: 'subject_h36m'
fr_margin: 10

# state net
#state_net_cfg: 'subject_h36m'
state_net_iter: 100

# training parameters
gamma: 0.95
tau: 0.95
#policy_v_net: tcn
#policy_v_net_param:
#  size: [64, 128]
#  dropout: 0.2
policy_htype: relu
policy_hsize: [300, 200]
policy_v_hdim: 128
policy_optimizer: 'Adam'
policy_lr: 5.e-5
policy_momentum: 0.0
policy_weightdecay: 0.0
#value_v_net: tcn
#value_v_net_param:
#  size: [64, 128]
#  dropout: 0.2
value_htype: relu
value_hsize: [300, 200]
value_v_hdim: 128
value_optimizer: 'Adam'
value_lr: 3.e-4
value_momentum: 0.0
value_weightdecay: 0.0
clip_epsilon: 0.2
min_batch_size: 50000
num_optim_epoch: 10
log_std: -2.3
fix_std: true
#fix_head_lb: 0.0
set_fix_start_state: true
cnn_feat_key: root_traj
max_iter_num: 3000
seed: 1
save_model_interval: 100
reward_id: 'followtraj_reward_v7'
reward_weights:
  w_rq: 0.0
  w_rp: 0.3
  w_rlvw: 0.0
  w_rlv: 0.9
  w_rav: 0.3
  w_vf: 0.0  # residual_force: False
  w_dof: 0.0  # joint_force
  w_bae: 0.0
  w_headh: 0.1
  w_eeh: 0.3
  k_rq: 100
  k_rp: 10
  k_rlvw1: 10.0
  k_rlvw2: 0.1
  k_rlv: 4.0
  k_rav: 2.0
  k_vf: 1
  k_dof: 0.0001
  k_bae: 1
  k_headh: 1
  k_eeh: 100

# expert and environment
mujoco_model: humanoid_h36m_v4
vis_model: humanoid_h36m_v4_vis
env_episode_len: 200
obs_coord: 'heading'
root_deheading: true
action_type: 'position'

# RFC parameters
residual_force: False
residual_force_scale: 100.0
#residual_force_mode: implicit

# extra control setting
meta_control: False
arm_reset: False
arm_pdclip: False

# masked training
ref_reset: True
#masked_freq: 30  # 10 for tcn, 30 for rnn

jkp_multiplier: 0.5
joint_params:
  # ["name", "k_p", "k_d", "a_ref", "a_scale", "torque_limit"]
  - ["Spine_x"           , 1000.0, 100.0,   0.0, 1.0, 200.0]
  - ["Spine_y"           , 1000.0, 100.0,   0.0, 1.0, 200.0]
  - ["Spine_z"           , 1000.0, 100.0,   0.0, 1.0, 200.0]
  - ["Spine1_x"          , 1000.0, 100.0,   0.0, 1.0, 200.0]
  - ["Spine1_y"          , 1000.0, 100.0,   0.0, 1.0, 200.0]
  - ["Spine1_z"          , 1000.0, 100.0,   0.0, 1.0, 200.0]
  - ["Spine2_x"          , 1000.0, 100.0,   0.0, 1.0, 200.0]
  - ["Spine2_y"          , 1000.0, 100.0,   0.0, 1.0, 200.0]
  - ["Spine2_z"          , 1000.0, 100.0,   0.0, 1.0, 200.0]
  - ["Spine3_x"          , 1000.0, 100.0,   0.0, 1.0, 200.0]
  - ["Spine3_y"          , 1000.0, 100.0,   0.0, 1.0, 200.0]
  - ["Spine3_z"          , 1000.0, 100.0,   0.0, 1.0, 200.0]
  - ["Neck_x"            ,  100.0,  10.0,   0.0, 1.0,  50.0]
  - ["Neck_y"            ,  100.0,  10.0,   0.0, 1.0,  50.0]
  - ["Neck_z"            ,  100.0,  10.0,   0.0, 1.0,  50.0]
  - ["Head_x"            ,  100.0,  10.0,   0.0, 1.0,  50.0]
  - ["Head_y"            ,  100.0,  10.0,   0.0, 1.0,  50.0]
  - ["Head_z"            ,  100.0,  10.0,   0.0, 1.0,  50.0]
  - ["RightShoulder_x"   ,  400.0,  40.0,   0.0, 1.0, 50.0]
  - ["RightShoulder_y"   ,  400.0,  40.0,   0.0, 1.0, 50.0]
  - ["RightShoulder_z"   ,  400.0,  40.0,   0.0, 1.0, 50.0]
  - ["RightArm_x"        ,  300.0,  50.0,   0.0, 1.0, 50.0]
  - ["RightArm_y"        ,  300.0,  50.0, -80.0, 1.0, 50.0]
  - ["RightArm_z"        ,  300.0,  50.0,   0.0, 1.0, 50.0]
  - ["RightForeArm_z"    ,  300.0,  30.0,  45.0, 1.0,  60.0]
  - ["RightHand_x"       ,  100.0,  10.0,   0.0, 1.0,  50.0]
  - ["RightHand_y"       ,  100.0,  10.0,   0.0, 1.0,  50.0]
  - ["RightHand_z"       ,  100.0,  10.0,   0.0, 1.0,  50.0]
  - ["LeftShoulder_x"    ,  400.0,  40.0,   0.0, 1.0, 50.0]
  - ["LeftShoulder_y"    ,  400.0,  40.0,   0.0, 1.0, 50.0]
  - ["LeftShoulder_z"    ,  400.0,  40.0,   0.0, 1.0, 50.0]
  - ["LeftArm_x"         ,  300.0,  50.0,   0.0, 1.0, 50.0]
  - ["LeftArm_y"         ,  300.0,  50.0,  80.0, 1.0, 50.0]
  - ["LeftArm_z"         ,  300.0,  50.0,   0.0, 1.0, 50.0]
  - ["LeftForeArm_z"     ,  300.0,  30.0, -45.0, 1.0,  60.0]
  - ["LeftHand_x"        ,  100.0,  10.0,   0.0, 1.0,  50.0]
  - ["LeftHand_y"        ,  100.0,  10.0,   0.0, 1.0,  50.0]
  - ["LeftHand_z"        ,  100.0,  10.0,   0.0, 1.0,  50.0]
  - ["RightUpLeg_x"      ,  600.0,  50.0,   0.0, 1.0, 600.0]
  - ["RightUpLeg_y"      ,  600.0,  50.0,   0.0, 1.0, 600.0]
  - ["RightUpLeg_z"      ,  600.0,  50.0,   0.0, 1.0, 600.0]
  - ["RightLeg_x"        ,  600.0,  50.0,  45.0, 1.0, 450.0]
  - ["RightFoot_x"       ,  400.0,  40.0,   0.0, 1.0, 300.0]
  - ["RightFoot_y"       ,  400.0,  40.0,   0.0, 1.0, 300.0]
  - ["RightFoot_z"       ,  400.0,  40.0,   0.0, 1.0, 300.0]
  - ["LeftUpLeg_x"       ,  600.0,  50.0,   0.0, 1.0, 600.0]
  - ["LeftUpLeg_y"       ,  600.0,  50.0,   0.0, 1.0, 600.0]
  - ["LeftUpLeg_z"       ,  600.0,  50.0,   0.0, 1.0, 600.0]
  - ["LeftLeg_x"         ,  600.0,  50.0,  45.0, 1.0, 450.0]
  - ["LeftFoot_x"        ,  400.0,  40.0,   0.0, 1.0, 300.0]
  - ["LeftFoot_y"        ,  400.0,  40.0,   0.0, 1.0, 300.0]
  - ["LeftFoot_z"        ,  400.0,  40.0,   0.0, 1.0, 300.0]

body_params:
  # ["name","diff weight"]
  - ["Spine"         , 5.0]
  - ["Spine1"        , 5.0]
  - ["Spine2"        , 5.0]
  - ["Spine3"        , 5.0]
  - ["Neck"          , 1.0]
  - ["Head"          , 1.0]
  - ["RightShoulder" , 5.0]
  - ["RightArm"      , 5.0]
  - ["RightForeArm"  , 5.0]
  - ["RightHand"     , 0.0]
  - ["LeftShoulder"  , 5.0]
  - ["LeftArm"       , 5.0]
  - ["LeftForeArm"   , 5.0]
  - ["LeftHand"      , 0.0]
  - ["RightUpLeg"    , 5.0]
  - ["RightLeg"      , 5.0]
  - ["RightFoot"     , 0.0]
  - ["LeftUpLeg"     , 5.0]
  - ["LeftLeg"       , 5.0]
  - ["LeftFoot"      , 0.0]